name: Deployment Dispatcher

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check tag format
        run: |
         tag_name="${{ github.ref }}"
          if [[ $tag_name =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Running production.yaml for tag: $tag_name"
            workflow_dispatch:
               inputs:
                 workflow: production.yaml
            # Run your production deployment steps here
          elif [[ $tag_name =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+-RC\.[0-9]+$ ]]; then
            echo "Running staging.yaml for tag: $tag_name"
            workflow_dispatch:
               inputs:
                 workflow: staging.yaml
            # Run your staging deployment steps here
          else
            echo "Tag format not recognized, skipping deployment."
            exit 78  # Exit with a neutral status code (78) to indicate skipping
          fi
          # tag_name="${{ github.ref }}"
          # if [[ $tag_name =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
          #   echo "Triggering production workflow for tag: $tag_name"
          #   # workflow_dispatch:
          #   #   inputs:
          #   #     workflow: production.yaml
          # elif [[ $tag_name =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+-RC\.[0-9]+$ ]]; then
          #   echo "Triggering staging workflow for tag: $tag_name"
          #   # workflow_dispatch:
          #   #   inputs:
          #   #     workflow: staging.yaml
          # else
          #   echo "Tag format not recognized, skipping deployment."
          #   exit 78  # Exit with a neutral status code (78) to indicate skipping
