name: Production application
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  build:
    name: Deployment process
    runs-on: ubuntu-latest
    steps:
      - name: Execute production deployment
        run: |
          echo "Deploying to production..."
