name: Production application
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  build:
    name: Deployment process
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        runner: [self-hosted, ubuntu-latest]
        max-parallel: [1]
    steps:
      - name: Execute production deployment
        run: |
          echo "Deploying to production..."
          TOKEN=${{ secrets.ATOKEN }}
          OWNER=${{ github.repository_owner }}
          REPO=${{ github.event.repository.name }}
          BRANCHES=$(curl -H "Authorization: token $TOKEN" -s "https://api.github.com/repos/$OWNER/$REPO/branches")
          echo "Branches: $BRANCHES"
