name: Production application
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  build:
    name: Deployment process
    strategy:
      matrix:
        runner: [self-hosted, ubuntu-latest]
    runs-on: ${{ matrix.runner }}
    timeout-minutes: 2  # Maximum 2-minute wait for self-hosted runner
    continue-on-error: ${{ matrix.runner == 'self-hosted' }}  # Allow fallback if self-hosted fails

    steps:
      - name: Execute production deployment
        run: |
          echo "Deploying to production..."
          TOKEN=${{ secrets.ATOKEN }}
          OWNER=${{ github.repository_owner }}
          REPO=${{ github.event.repository.name }}
          BRANCHES=$(curl -H "Authorization: token $TOKEN" -s "https://api.github.com/repos/$OWNER/$REPO/branches")
          echo "Branches: $BRANCHES"
