name: Production application

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  deploy-self-hosted:
    name: Deployment on Self-Hosted Runner
    runs-on: self-hosted
    timeout-minutes: 1  # Set timeout to 2 minutes
    continue-on-error: true  # Allow fallback if it fails

    steps:
      - name: Execute production deployment
        run: |
          echo "Deploying to production on self-hosted..."
          TOKEN=${{ secrets.ATOKEN }}
          OWNER=${{ github.repository_owner }}
          REPO=${{ github.event.repository.name }}
          BRANCHES=$(curl -H "Authorization: token $TOKEN" -s "https://api.github.com/repos/$OWNER/$REPO/branches")
          echo "Branches: $BRANCHES"

  deploy-ubuntu:
    name: Fallback to Ubuntu Runner if Self-Hosted Fails
    runs-on: ubuntu-latest
    needs: deploy-self-hosted  # This job runs only if the previous job fails
    if: failure()  # This job runs only if the self-hosted job fails

    steps:
      - name: Execute production deployment
        run: |
          echo "Self-hosted runner failed, deploying to ubuntu-latest..."
          TOKEN=${{ secrets.ATOKEN }}
          OWNER=${{ github.repository_owner }}
          REPO=${{ github.event.repository.name }}
          BRANCHES=$(curl -H "Authorization: token $TOKEN" -s "https://api.github.com/repos/$OWNER/$REPO/branches")
          echo "Branches: $BRANCHES"
