name: staging application2
on:
  push:
    tags:
      -  'v[0-9]+.[0-9]+.[0-9]+-RC.[0-9]+'
      # - "v*.*.*-RC.*"

jobs:
  build:
    name: Staging Deployment process
    runs-on: ubuntu-latest
    steps:
      - name: Execute deployment
        run: |
          echo "Deploying to stagingg..."
